### ISSUE TITLE
Fix and re-enable disabled MPI job dispatcher tests

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Herbert#126]
Disabled tests:
- test_job_dispatcher_parpool.m
  - test_job_submittion
  - test_job_fail_restart

- test_job_dispatcher_mpiexec.m
  - test_job_fail_restart - Windows Only
  - test_job_with_logs_3workers - Windows Only

**Comment by abuts** [comment]
Partially addressed in PR #173, branch #159

**Comment by abuts** [comment]
fixed by #159 #174 #191 #189 #187. All Herbert tests are enabled and successfully passing.
