### ISSUE TITLE
Merge use_mex and use_mex_C config settings

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Herbert#150]
https://github.com/pace-neutrons/Herbert/pull/148 removed the Fortran routines from the codebase. We therefore have no more need for the `use_mex` setting as that referred only to the Fortran mex files. We should remove the `use_mex` setting and then rename the `use_mex_C` setting to `use_mex`.

**Outputs:**
- `use_mex` setting referring to Fortran routines removed
- Code using the `use_mex` setting updated
- `use_mex_C` setting renamed to `use_mex`

**Comment by hsautessella** [comment]
We should carefully consider what effect replacing the setting will have on previously saved configurations that will contain both settings. Some tests to ensure backwards compatibility would be good

**Comment by abuts** [comment]
fixed as part of [PR#164](https://github.com/pace-neutrons/Herbert/pull/164)
