### ISSUE TITLE
Some user installation modes fail

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#157]
Recent packages packs Horace and Herbert core code into an archive, adds horace_on, herbert_on scripts to top of the packages folder and provides it to users. 

One way of installing package known to users is adding to Matlab path location of horace_on/herbert_on scripts and modifying these scripts to refer to Horace/Herbert folders where init files are located. 

If user unpacks the package and adds to Matlab path the path to the folder where Horace/Herebert pacakages are and horace_on/herbert_on scripts are located, installation fails. It works for the first time, but second time folder with horace_on/herbert_on scripts are removed from the path. 

Users are confused. 

Suggestions:
Modify horace_on/herbert_on scripts provided with the package in a way, that users do not need to modify internal path-s within the packages if these files are not moved anywhere. 

The top-package folder should not be removed from the Matlab path.

**Comment by nickbattam-tessella** [comment]
The `horace_on`/`herbert_on` is removing all previous instances of the Horace/Herbert from the path. Doing so, in the installation set described, it removes references to itself and its a bug to fix.
