### ISSUE TITLE
Effective data serializer for large messages 

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#215]
Current implementation of CPP framework (and any other frameworks) use custom serializer to prepare messages for transfer through their appropriate channels. 

When the data messages are large, this may become very inefficient as multiple memory reallocations are happening during this serialization. 

In addition to that, pixel data on disk are 4-bytes data when in memory they are 8-bytes data.  It make a lot of sense to reduce the size of the data while transferred through the MPI channels during serialization. 

The solution for these issues is to write C++ serializer for large data messages. 
This serializer will be primary used with CPP framework, but can be deployed with other frameworks too.

**Comment by cmarooney-stfc** [comment]
no docs changes required
