### ISSUE TITLE
Move SL7 Jenkins pipelines to use Matlab R2019b

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Herbert#218]
ANVIL now has Matlab R2019b available. We should move all the pipelines using Matlab R2019a to use Matlab 2019b.

To do this you should:

- [ ] Rename the `X-Scientific-Linux-7-2019a` to `X-Scientific-Linux-7-2019b`
- [ ] Update the `X-Scientific-Linux-7-2019b` pipelines so that the default value for parameter `MATLAB_VERSION` is `R2019b`.
- [ ] Update the job name in the Nightly-Trigger job list to match

**Comment by cmarooney-stfc** [comment]
Pipelines for master and PR now changed. About to change branch to make 2019a to 2019b and remove existing 2019b which was for testing

**Comment by cmarooney-stfc** [comment]
Pipelines updated. Temporary branch pipelines deleted. pace-neutrons/Horace#342 moved to completed.
