### ISSUE TITLE
bug in configuration if parallel worker is not available 

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#250]
if `worker_v2` is not present on search path, the current herbert/horace installation fails. This is because of outdated code within parallel_config class, which is clear bug

**Comment by nickbattam-tessella** [comment]
Error reported: 

```
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
MATLAB:noSuchMethodOrField
Unrecognized method, property, or field 'parallel_framework_' for class
'parallel_config'.
```

 [init_error.log](https://github.com/pace-neutrons/Herbert/files/5502129/init_error.log)

**Comment by abuts** [comment]
fixed ages ago. PR for some reason have not closed this ticket
