### ISSUE TITLE
changes, related to urange clarification

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#269]
This is ticket to include appropriate changes for Horace ticket [#447](https://github.com/pace-neutrons/Horace/issues/447), related to urange clarification

**Comment by cmarooney-stfc** [comment]
@abuts Hi Alex, checking that this Herbert ticket is still blocking Horace #447?

**Comment by abuts** [comment]
well, these changes are necessary for Horace#447. It is blocking for it. I will merge it as soon as #447 is completed. Some tests in #447 are still failing and though I hope no changes here are necessary to fix it, I keep it open until all changes in #447 are done.

**Comment by cmarooney-stfc** [comment]
@abuts Hi Alex, it looks as if this is finished as the associated Horace #447 is now closed. Can we close this one please?
