### ISSUE TITLE
Add missing sigvar unary and binary operations tests

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Herbert#272]
There are no numerical tests of the operations defined on the sigvar object, used by the Horace SQW, PixelData and DnD objects.

These should be added for each `<operation>_single.m` implementation, testing scalar and array valued arguments. Special attention is required for validation of the error calculations as there are typically non-trivial calculations..

**Comment by oerc0122** [comment]
Done for pixels and applied via calls to `sqw_eval` passed to pixels.
