### ISSUE TITLE
Update version of CMake used on Linux builds

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Herbert#278]
CMake 3.19 is now available on ANVIL's SL7 machines. We should update the `Jenkinsfile` so that the Linux builds use CMake 3.19 instead of 3.7. We should also update the `cmake_minimum_required_version` in the top level CMakeLists.txt file, We're using CMake 3.15.2 on Windows, so I suggest we make this our minimum.

This will allow us to use more convenient CMake features that were missing in 3.7. For example, when we link to MPI, we can now do:
```CMake
add_library(my_library ${SRC})
target_link_libraries(my_library PRIVATE MPI::MPI_CXX)
```

rather than

```CMake
add_library(my_library ${SRC})
target_link_libraries(my_library PRIVATE ${MPI_CXX_LIBRARIES}
target_include_directories(my_library PRIVATE ${MPI_CXX_INCLUDE_PATH}
```

Using this newer syntax is more concise and also more resistant to library linking requirements changing in the future.

We could also look into removing `Herbert/cmake/external`, as this directory holds a `FindMatlab` script from a newer CMake version, as we had some problems with the 3.7.2 version. We might also look into using `BUILD_RPATH` in `_LowLevelCode/cpp/cpp_communicator/CMakeLists.txt` as there's a workaround there due to the feature not working on 3.7.2 (these are probably both separate issues).

**Comment by cmarooney-stfc** [comment]
@hsautessella Hi Harry, looking at the sensible-looking suggestions in the last paragraph of the description and wondering if they are captured in a backlog ticket? thanks Chris
