### ISSUE TITLE
Obsolete `exist`

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Herbert#286]
`exist` involves magic numbers which make code inherently more confusing. More recent versions of MATLAB include some functions which do not include magic numbers (such as `isfolder`), but due to desire for backwards compatibility, these cannot be used yet. 

Suggest implementing Horace specific one-liners to perform the check clarifying the code and allowing easier transition to new forms if/when they become available.

**Comment by nickbattam-tessella** [comment]
For the Herbert helper functions we can call the new MATLAB functions (e.g. `isfolder`) or wrap `exist( ) == n` calls if these are not available. 

The xunit test code should not use the implementation in `herbert_core/utilities/files`, so will need a duplicate implementation of `is_folder` defining.

**Comment by nickbattam-tessella** [comment]
Note: it is only the 'file' exist check that has multiple return values, the others return 0 or n
