### ISSUE TITLE
Ensure consistent file encoding

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Herbert#294]
Source tree includes files not in UTF-8 encoding.

These should be converted for consistency. Problem identified during MLint analysis

- `herbert_core/utilities/maths/randraw.m` is `windows-1252`

**Comment by nickbattam-tessella** [comment]
Related to #291

**Comment by nickbattam-tessella** [comment]
[encoding.log](https://github.com/pace-neutrons/Herbert/files/5959116/encoding.log)

**Comment by cmarooney-stfc** [comment]
@nickbattam-tessella Hi Nick, the equivalent Horace ticket #561 has been closed - checking if this one is really still open. Thanks
