### ISSUE TITLE
Serialize MException

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#36]
This is part of bigger Horace ticket https://github.com/pace-neutrons/Horace/issues/70 on asynchronous communications. These communications request messages serialization and custom serialization needs to be deployed. Unfortunately, Matlab MException class, used in all Matlab error can not be serialized by existing tools, so small addition to messages, asllowing to serialize this class is necessary for proper MPI framework operations.

**Comment by hsautessella** [comment]
closed by #38
