### ISSUE TITLE
dl and pl methods issue

### ISSUE THREAD

**Issue by russellewings** [pace-neutrons/Herbert#395]
The IX_dataset_1d methods dl and pl (for plotting lines) are failing. It looks like it might be something to do with when there are zeros in the signal and/or error arrays. The symptom is a set of blank axes being produced. Using an alternative method such as "plot", pp, pm, etc does work as expected, and plots something for cases where dl and pl fail.

**Comment by cmarooney-stfc** [comment]
@russellewings Hi Russell, thanks for submitting this. The easiest way to check this is to get access to your data so we can see dl and pl failing and compare it with other issues. Is this possible? Thanks CHris

**Comment by cmarooney-stfc** [comment]
@russellewings Also checking which release you're working with

**Comment by russellewings** [comment]
@cmarooney-stfc I have shared the IDAaaS VM that I'm using with you (yourself and Alex added - let me know if others required). The Horace / Herbert version is '3.6.1 dev'. The machine ID is host-130-246-215-228.nubes.stfc.ac.uk and if you look at the Matlab session that's live in there you'll see a script called PlottingBug_PACE that should allow the issue to be reproduced.

**Comment by cmarooney-stfc** [comment]
Or is it now the ZrWO_100K file in the script directory (which I will grab)

**Comment by abuts** [comment]
Apparently the issue for this data is caused by the fact that every second point of the data is NaN so straight line can not be plotted. 
I will add warning message, which would inform users that such data can not be plotted as a line and routine which plots points instead should be used to see anything
