### ISSUE TITLE
herbert's opt_config_manager fails if users put Horace_init on the path

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#42]
opt_config_manager helps users to configure their machines. Its oddity is that it is located in Herbert but need to know about Horace configurations. 

If user, sets up Horace as described in [method 1](http://horace.isis.rl.ac.uk/Download_and_setup#Standard_Installation), horace fails. This is a bug which should be fixed.

**Comment by hsautessella** [comment]
#closed by #43
