### ISSUE TITLE
Changes to oriented lattice and rundata to work with gen_sqw better

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Herbert#430]
There are three classes which doing the similar things in Horace. IX_samp, oriented_lattice and IX_experiment. 
In addition to that, gen_sqw does the checks, these classes do. The ticket is to improve integration between these three classes and gen_sqw

**Comment by cmarooney-stfc** [comment]
@abuts Hi Alex - is this just stalled waiting for your other work, or abandoned? Can we close it?
