### ISSUE TITLE
fortran mex

### ISSUE THREAD

**Issue by liugx1997** [pace-neutrons/Herbert#433]
Hello teacher, I would like to ask you about the problem of FORTRAN invocation by MATLAB. I am running MATLAB on Windows, and I have generated mexW64 file, but it will crash if I use MATLAB to call. Could you help me find the problem?

**Comment by cmarooney-stfc** [comment]
@liugx1997 Dear Liugx1997. You have added this issue to a repository for the PACE project, not a class for MATLAB. Please could you say who you are trying to communicate with. thanks
