### ISSUE TITLE
Decide which test files should be packaged

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Herbert#57]
Horace requires the matlab xUnit test framework that lives within Herbert. This means for Horace to be fully functional with a packaged version of Horace, the xUnit framework must also be shipped.

#56 packages the entire `_test` directory with Herbert. We should work out just how much of that directory is needed and ship as little as possible as we can. We should consider the possibility of moving the xUnit framework out of the `_test` directory if it is going to be something that other packages require Herbert to have (it essentially becomes part of the Herbert library - whether this is something we want should be discussed)

Outputs:
- A decision on what directories are required to be packaged
- Have CMake package only the required files
- New Horace issue ticket to update references to moved files

**Comment by nickbattam-tessella** [comment]
The `_test/matlab_xunit` and `_test/matlab_xunit_ISISextras` folders (i.e. the "test library") should definitely be separated from the Herbert test files.

Whether these move to `Herbert/herbert_core/utilities/tests` (which is then included as the `utilities` folder is already included). or `Herbert/tools/`.

The scope of this work overlaps with https://github.com/pace-neutrons/Horace/issues/84 - if the outcome of that is to create an third `pace-common` git repository to contain the shared CMake functions this library potentially belongs with that.

**Comment by hsautessella** [comment]
The plan (discussed offline) is to pull the xunit test framework out of the `_test` directory and for it to become part of the "Herbert library".

**Comment by hsautessella** [comment]
Also discussed, was the creation of a `templates` directory to store the `hebert_on`/`worker_v2` scripts

**Comment by hsautessella** [comment]
Closed by https://github.com/pace-neutrons/Herbert/pull/87
