### ISSUE TITLE
IO race conditions on Windows Jenkins

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Herbert#82]
Now that there are multiple workers on the Windows Jenkins server, we are getting errors due to IO race conditions. Some tests write to the user's temporary directory, this means that the two separate jobs are attempting to write to the same place causing IO errors.

**Comment by nickbattam-tessella** [comment]
MATLAB tests need to be reconfigured to write to `$MATLAB_TMP/<guid>/` to avoid this problem.

The system directory can be accessed via `tempdir` and updated with `setenv()` `TEMP`(windows), `TMP`(linux).
 
https://uk.mathworks.com/matlabcentral/answers/97720-how-do-i-change-the-temporary-directory-that-matlab-uses
